name: Docker Image CI

on:
  push:
    branches: ["Develop"]
  pull_request:
    branches: ["Develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.folongzidane }}
          password: ${{ secrets.folongzidane }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: folongzidane/folongzidane-app:latest

      - name: Deploy to server
        run: |
          ssh username@your-server "docker pull folongzidane/folongzidane-app:latest && docker-compose -f /path/to/docker-compose.yml up -d"
